title: Сайт-Портфолио html-верстальщика Сергея Закирова
description: Я профессионально занимаюсь версткой сайтов, адаптивно и кроссбраузерно. На этом сайте вы можете ознакомится со списком моего портфолио.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sezak.ru" # the base hostname & protocol for your site, e.g. http://example.com

metrika: true

socials:
  telegram: https://t.me/sezak74
  vk: https://vk.com/id614911269
  github: https://github.com/lorsalio7
  email: erega74@gmail.com

highlighter: none

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-toc

plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-paginate-v2, jekyll-toc]

toc:
  ordered_list: true

pagination:
  enabled: true
  per_page: 6
  sort_field: 'date'
  sort_reverse: true
  limit: 0


imagehome: "img/imagehome.jpg"



# paginate: 1
# # enabled: true
# paginate_path: "/category/page:num/"
# # paginate: 6


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

# {% else %}
# <a class="button button--disabled portfolio__button">Назад</a>

# {% else %}
# <a class="button button--disabled portfolio__button">Вперед</a>

lang: ru_RU

exclude:
  - gulpfile.js
  - package-lock.json
  - package.json
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
